[[menus.main]]
name = "Homepage"
url = "/"
weight = 10

[[menus.main]]
name = "Über uns"
url = "/ueber-uns/"
weight = 20

[[menus.main]]
name = "Kontakt"
parent = "Über uns"
url = "/ueber-uns/kontakt/"
weight = 21

[[menus.main]]
name = "Aktuelles"
url = "/aktuelles/"
weight = 30

# [[menus.main]]
# name = "Was wir machen"
# url = "/was-wir-machen/"
# weight = 40

[[menus.main]]
name = "Workshops & Veranstaltungen"
url = "/workshops/"
weight = 40

[[menus.main]]
name = "Podcasts"
url = "/podcasts/"
weight = 50

[[menus.main]]
name = "Materialien"
url = "/materialien/"
weight = 60

[[menus.main]]
name = "Inhalte & Beiträge"
parent = "Materialien"
url = "/materialien/inhalte-beitraege/"
weight = 61

[[menus.main]]
name = "Zine"
parent = "Materialien"
url = "/materialien/zine/"
weight = 62

[[menus.main]]
name = "Collagen"
parent = "Materialien"
url = "/materialien/collagen/"
weight = 63

[[menus.main]]
name = "Gruppenneugründung"
parent = "Materialien"
url = "/materialien/gruppenneugruendung/"
weight = 64

[[menus.main]]
name = "Links"
url = "/links/"
weight = 70