# backend:
#   name: github
#   repo: ShaQay3Q/sichtbar-und-selbstbestimmt
#   branch: main

backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Wer wir sind"
        name: "about"
        file: "content/pages/wer-wir-sind.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Kontakt"
        name: "kontakt"
        file: "content/pages/kontakt.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "podcasts"
    label: "Podcasts"
    folder: "content/podcasts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Audio File", name: "audio", widget: "file" }
      - { label: "Description", name: "body", widget: "markdown" }
