backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    format: frontmatter
    files:
      - label: "Wer wir sind (Homepage)"
        name: "homepage"
        file: "content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Kontakt"
        name: "kontakt"
        file: "content/pages/kontakt.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Links"
        name: "links"
        file: "content/pages/links.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Workshops"
        name: "workshops"
        file: "content/projects/workshops.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Vorträge"
        name: "vortraege"
        file: "content/projects/vortraege.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "podcasts"
    label: "Podcasts"
    folder: "content/podcasts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Audio File", name: "audio", widget: "file" }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - {
          label: "Duration",
          name: "duration",
          widget: "string",
          required: false,
        }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Galerie"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Bild",
          name: "image",
          widget: "image",
          hint: "Ein Bild auswählen oder hochladen",
        }
      - {
          label: "Beschreibung",
          name: "body",
          widget: "markdown",
          required: false,
        }
